In [1]:
print("Ajay")

Ajay


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

In [5]:
X=np.array([[1],[2],[2.5],[2.9],[3.1],[5.3],[5.7],[6.3],[7],[7.5],[8]])

Pass=1,
Fail=0

In [6]:
print(type(X))

<class 'numpy.ndarray'>


In [38]:
y=np.array([0,0,0,0,0,1,1,1,1,1,1])

Train test split

In [8]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=14
)

In [9]:
X_train

array([[5.3],
       [3.1],
       [2.5],
       [7.5],
       [2. ],
       [6.3],
       [5.7],
       [7. ]])

In [10]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 1])

In [11]:
X_test

array([[2.9],
       [8. ],
       [1. ]])

In [12]:
y_test

array([0, 1, 0])

In [13]:
M=LogisticRegression()

In [14]:
M.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred=M.predict(X_test)

In [16]:
y_pred

array([0, 1, 0])

In [17]:
accuracy=accuracy_score(y_test,y_pred)
print("accuracy_score", accuracy)

accuracy_score 1.0


In [22]:
Hours = np.array([[5.3],
                  [3.1]])


In [23]:
output=M.predict(Hours)

In [27]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy_Score:",accuracy)

Accuracy_Score: 1.0


In [37]:
Classification=classification_report(y_test,y_pred)
print("C_R", Classification)

C_R               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [53]:
new_hours = 8

prediction = M.predict([[new_hours]])


In [54]:
if prediction[0] == 1:
    print("Pass!!!!!!!!!!!")
else:
    print("Fail!!!!!!!!!111")

Pass!!!!!!!!!!!
